name: build

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: 'compile and push'
    runs-on: ubuntu-latest

    steps:
    - name: 'git clone --recursive'
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: 'compile ./*.tex files'
      uses: xu-cheng/latex-action@master
      with:
        working_directory: ./
        root_file: | 
          mlightdp.tex
          ssmg-complexity.tex
          one_minute_madness.tex

    - name: 'compile ./adiar/*.tex files'
      uses: xu-cheng/latex-action@master
      with:
        working_directory: ./adiar/
        root_file: | 
          adiar_core.tex
          adiar_core.conference.tex

    - name: 'remove external/*.pdf files'
      run: |
        rm -rf external/*.pdf

    - name: 'mv *.pdf files'
      run: |
         mkdir out
         mkdir out/adiar
         for f in **/*.pdf ; do mv $f out/$f; done
         for f in *.pdf ; do mv $f out/$f; done

    - name: 'git push'
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: out
        FOLDER: out
  
