name: build

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: 'compile and push'
    runs-on: ubuntu-latest

    steps:
    - name: 'git clone --recursive'
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: 'compile ./*.tex files'
      uses: xu-cheng/latex-action@master
      with:
        working_directory: ./
        root_file: |
          adiar_core.tex
          adiar_core.tacas22.tex
          adiar_core.movep22.tex
          adiar_cuts.tex
          adiar_nested_sweeping.tex
          adiar_random-access.tex
          adiar_zdd.tex
          io_efficient_computation.tex
          mlightdp.tex
          MSc_thesis.tex
          one_minute_madness.tex
          ssmg-complexity.tex

    - name: 'remove external/*.pdf files'
      run: |
        rm -rf external/*.pdf

    - name: 'mv *.pdf files'
      run: |
         mkdir out
         for f in *.pdf ; do mv $f out/$f; done

    - name: 'git push'
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: out
        FOLDER: out
